# setup-app.yml
---
  - hosts: webservers
    become: true
    tasks: 
      - name: Upload index.php file
        copy:
          src: ../index.php
          dest: /var/www/html
          mode: 0755

      - name: Configure php.ini file
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=On'
        notify: restart httpd